api/package-lock.json
api/package.json
api/routes/layer.js

The ETL server expects GeoJSON features to be posted to the cot route but currently does not check the validity of the GeoJSON. Although layers are inherently trusted sources of data, we should perform validity checking to ensure a developer doesn't accidentally submit a poisoned request body.

Add GeoJSON validity checking

---

api/lib/aws/lambda.js
cloudformation/lib/api.js

Lambda Tasks currently fail silently and there is no way to determine their state via the ETL UI. This PR introduced a CloudWatch Metric that will be created alongside the lambda and track invocation errors and alarm if there are >0 errors/min.
In a subsequent PR we can then add a `layer.status` prop much like `connection.status` that is populated based on the alarm/not alarm state of this metric. This will in turn allow us to actually use the "green" status icon next to a layer in the same way we have been with connections.

Lambda Task Alarms

---

api/lib/style.js
cloudformation/lib/api.js

I started playing with the query style API and the layer went into an alarm state (the new alarm code works! :tada:)
Digging in made me realize that although the style API mutates the feature with the correct style properties, it only returns the feature if using the basic style endpoint, resulting in a 5xx error.

:bug: Ensure Feature is Returned

---

cloudformation/lib/db.js

Lack of Enhanced Monitoring on our RDS Instances resulted in them being terminated until monitoring was added.

Add Enhanced Monitoring

---

api/lib/types/basemap.js
api/routes/basemap.ts
api/schema/req.query.ListBaseMaps.json
api/web/src/components/BaseMap/Location.vue
api/web/src/components/Data/Location.vue

While importing the All The Maps Topo layer many of the sources failed to display in the UI. Upon further digging this is due to one of two reasons
- HTTP tile source resulting in an mixed content warning when used by the HTTPS UI
- CORS issue in that the layer does not have wildcard cors headers
- Add `order` param to BaseMap API
- Add `sort` param to BaseMap API
- Add Proxy Implementation to avoid CORS issue

Basemap Proxy

---

api/lib/aws/lambda.ts
api/lib/types/layer.js
api/package-lock.json
api/routes/layer.ts
api/schema/req.query.ListLayers.json
api/web/package-lock.json
api/web/src/components/Layer/LayerDeployment.vue
api/web/src/components/LayerAdmin.vue
api/web/src/components/Layers.vue
api/web/src/components/util/TableFooter.vue
api/web/src/components/util/TableHeader.vue
api/web/src/main.js

Anytime a change is made to the underlying CloudFormation, a redeploy is required to every layer to bring it up to date. At this time that involves manually editing every single layer to make a deploy inducing change to the layer, waiting for the deploy to complete and then deploying again to return the changed property to it's initial value.
This PR introduces a per-layer and global `/redeploy` endpoint to save hours of time when a redeployment is needed. It also introduces a new LayerAdmin component which will continue to be built out to support server-wide layer operations

Re-Deploy Layers

---

api/web/src/components/Connection/ConnectionLayer.vue
api/web/src/components/Data/DataLayer.vue
api/web/src/components/LayerEdit.vue
api/web/src/main.js
api/web/src/stores/cots.ts

When we create a layer we formerly had a dropdown list to allow the user to select a connection or data ID. We're getting enough layers and data sources that they don't fit in a single list. As everything is migrating to live under a single connection associated to an agency, they PR removes the Data/ConnectionID Selection and infers it automatically from the URL

Add Layer Create

---

api/routes/profile.ts
api/routes/search.ts

If a user hasn't yet set a TAK Profile Location and attempts to update profile settings, the update fails as `tak_loc: null` is not allowed by the API.
This PR allows for `tak_loc` to be set to null

Add Null Loc allowance

---

api/web/src/components/Layers.vue

Layers are now strictly created from within a connection, remove the New Layer button from the layers page

Remove Layer Button

---

api/routes/connection.ts
api/routes/data.ts

If a database integrity rule is violated during deletion, a 5xx error is issued. This PR adds checks before deletion of common types that will generate a 4xx error with a human readable description of how to rectify the error

Human Readable Delete Errors

---

api/package-lock.json
api/routes/config.ts
api/web/src/components/Admin/AdminConfig.vue

We need a fairly flexible location for non-critical settings in the ETL Server that aren't directly 1:1 related to the TAK Server
This builds upon the `settings` table by allowing `PUT` requests to updating pre-defined keys in the the table
Immediately: this will allow enabling & storing an AGOL token for a subsequent PR to enable a User Input box on the map interface for Geocoding

Allow Editing Server Settings

---

api/index.ts
api/lib/config.ts
api/lib/models.ts
api/lib/provider.ts
api/lib/schema.ts
api/migrations/0038_tan_hiroim.sql
api/migrations/meta/0038_snapshot.json
api/migrations/meta/_journal.json
api/package-lock.json
api/test/flight.ts
cloudformation/lib/api.js

Now that we have System Admin, Agency Admin, & User distinctions implemented accross the API, this PR removes the AuthGroup requirement in favour of the TAK server determining ACL

Remove AuthGroup

---

api/web/src/App.vue
api/web/src/components/Login.vue

If you click a link and haven't logged in, it loses the state of the link when you are redirect to the login page.
This PR introduces a `?redirect` which will be appended to the `/login` route and redirected to if successful

Redirect State on Login

---

api/lib/connection-pool.ts
api/web/src/components/CloudTAK/Map.vue
api/web/src/derived-types.d.ts
api/web/src/stores/connection.ts
api/web/src/stores/cots.ts
api/web/src/stores/map.ts

CoTs that came through the TLS stream were formerly added to the general store.
This PR monitors for the mission change notification preceding the CoT and assigns it to the relevant mission.

Add/Remove CoTs from Mission

---

api/package-lock.json
api/web/package-lock.json
api/web/package.json
api/web/public/logos/icons.js
api/web/src/components/CloudTAK/Map.vue
api/web/src/components/CloudTAK/Menu.vue
api/web/src/components/CloudTAK/util/MultipleSelect.vue
api/web/src/components/Connection/ConnectionGroups.vue
api/web/src/stores/cots.ts
api/web/src/stores/cots/cot.ts
api/web/src/stores/map.ts
api/web/tsconfig.json

Our last big update was diff based rendering which sped up rendering tremendously as only features that came through the socket would be upserted. This is great until you run into a layer like the lightening layer where large numbers of essentially unchanging features come through the socket and are rendered.
This PR introduces the following:
- Introduces a COT class that implements the `Feature` type and serves as a container for helper fns
- Introduces an `as_rendered()` fn which only builds a feature with the minimum properties needed to render it on the map
TODO:
Ref: https://github.com/dfpc-coe/CloudTAK/issues/264

Conditional Rendering (Stage 1)

---

api/web/src/stores/cots.ts

From:
To:
Absolutely enourmous speedup that is due to the cost of creating `moment` date objects. The moment library has been removed completey from the re-render/diff code in favour of two unix timestamps being created - one for the current time, and one for the stale time of each COT which are then compared. Average time in the update loop went from ~300ms to ~50-75ms

Lightening Fast

---

api/lib/sinks.ts

I'd originally set the MessageGroupId in the FiFo queue to be the Sink ID with the understanding that I wanted CoTs to be processed in order as the "latest" CoT needs to be the last processed out of a list. We've seen significant bottlenecks for large CoT submissions to the sink API which were alleviated significantly in a prior PR which introduces parallelism within the FiFo batch of 10 messages.
This should further reduce queue congesion by instead limiting processing by Sink ID and then secondarily by CoT UID. Thereforce each CoT UID has to be processed in order but CoTs within a given sink can be processed in parallel.

Increase Throughput

---

api/web/src/App.vue

If an expired token was used, an error would be thrown despite already being at the login page

Fix Login Error

---

api/web/src/components/CloudTAK/Map.vue
api/web/src/components/CloudTAK/util/Coordinate.vue
api/web/src/components/CloudTAK/util/CopyField.vue

- **Smarter Location tracking**
- **Show live location status**

SmarterLocations

---

api/lib/style.ts
api/test/style.test.ts

Allow a custom handlebar funtion for falling back between values:
```
{{fallback none1 none2 yes1 none3 yes2}}
```
The first truthy value will be used

Fallback Syntax and Tests

---

api/lib/api/mission-log.ts
api/package-lock.json
api/routes/marti-mission-logs.ts
api/routes/marti-mission.ts
api/test/fixtures/get_schema.json
api/test/server.srv.test.ts
api/web/package-lock.json
api/web/src/components/CloudTAK/Menu/Mission.vue
api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue
api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue
api/web/src/components/CloudTAK/util/Video.vue
api/web/src/derived-types.d.ts
api/web/src/stores/cots.ts
api/web/src/types.ts

Start to experiment with some of the action items in https://github.com/dfpc-coe/CloudTAK/issues/369
Closes: https://github.com/dfpc-coe/CloudTAK/issues/341

LiveStream logs

---

api/web/src/components/CloudTAK/Map.vue
api/web/src/components/CloudTAK/RadialMenu/RadialMenu.vue

Implement a Locked State Enablement that is accessible both via the Radial Menu and the CoT Viewer when the Feature is a `CoT` and of Geometry Type `Point`
Closes: https://github.com/dfpc-coe/CloudTAK/issues/223

Locked Radial

---

api/index.ts
api/lib/aws/s3.ts
api/package-lock.json
docker-compose.yml

There is a strong desire to target a local deployment of the main CloudTAK map. This PR represents an initial effort to automatically configure minio as an alternative local S3 compatible store when running via docker-compose

CloudTAK Local Support - Minio Store

---

api/lib/control/video-service.ts
api/routes/video-lease.ts
api/web/src/components/Admin/Videos/AdminVideoLeases.vue
api/web/src/components/CloudTAK/Menu/Videos.vue

The database and UI currently allow you to set a Video Lease as allowing management from anyone that is a member of a user determined channel
This wires up this functionality in the auth & UI levels, allowing leases that have been locked to a channel to be managed by any users within that channel.

Video Lease Channels

---

api/routes/marti-mission.ts

Changes the creatorUid when creating missions to match the UID used elsewhere in CloudTAK. This solves an error I was getting while updating OpenTAKServer to work with CloudTAK.

Set the creatorUid to `ANDROID-CloudTAK-${user.email}` when creating missions

---

api/.gitignore
api/index.ts
api/lib/api/credentials.ts
api/lib/initialization.ts
api/lib/models.ts
api/lib/schema.ts
api/lib/types.ts
api/migrations/0081_fluffy_loners.sql
api/migrations/meta/0081_snapshot.json
api/migrations/meta/_journal.json
api/package-lock.json
api/routes/basemap.ts
api/routes/connection.ts
api/routes/icons.ts
api/routes/profile-interest.ts
api/test/connection.srv.test.ts
api/test/fixtures/get_schema.json
api/test/flight.ts
api/web/package-lock.json
api/web/src/components/CloudTAK/CoTView.vue
api/web/src/components/CloudTAK/Map.vue
api/web/src/components/CloudTAK/Menu/Connections.vue
api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue
api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue
api/web/src/components/CloudTAK/RadialMenu/RadialMenu.vue
api/web/src/components/CloudTAK/util/ChannelInfo.vue
api/web/src/components/CloudTAK/util/CoordinateType.vue
api/web/src/components/CloudTAK/util/DrawOverlay.vue
api/web/src/stores/map.ts

- Rewrite Connection Pane in TS
- Use `menu` & `menuitem` for accessibility
- Rewrite MissionContents in TS and remove a ton of unused cruft and fix a bunch of bugs around showing imports related to that mission
- Update to latest node-cot which supports `strict:false` mode for automatically converting an invalid DataPackage into a valid one
- Use the new `strict: false` mode for automatically importing default Iconsets on a newly provisioned server
- Move all the initial loading code to the `Bulldozer` class which runs on server startup

Holiday Grab Bag

---

api/routes/config.ts

If a custom TAK Group name is not set the `group::` prefix is shown to the user when it shouldn't be and is correctly rejected if selected by the PATCH Profile API
This PR fixes the API response when getting the group list by automatically removing the `group::` prefix

Fix Default Groups

---

api/package-lock.json

Some CoT markers coming in via the historic CoT API were missing a callsign and therefore failed the node-cot parsing
This PR makes the callsign field optional

BreadCrumb Fix

---

api/lib/config.ts
api/package-lock.json
cloudformation/lib/api.js
docker-compose.yml

The PMTiles server was rewritten to support both AWS hosted (via lambda/api gateway) and "local" (via express server) operations in the same codebase.
I didn't however set this in the DockerCompose to actually wire it up

PMTiles URL

---

api/package-lock.json
api/routes/marti-package.ts
api/web/package-lock.json
api/web/src/components/Login.vue

- Implement a check when a file is uploaded via the DataPackage context to see if the upload is already in the DataPackage format and if so just pass it through instead of "double zipping" it
- If the upload is not a DataPackage, fall back to creating a new DataPackage in which this upload will be added as a file
- :bug: Fix proper closing of the Zip reader Node-COT Library
- :rocket: Automatically remove the source zip when the DataPackage is parsed.

Don't Double Zip DataPackages

---

api/web/src/components/PageFooter.vue

- Now reads "State of Colorado" instead of "Static of Colorado". Also added a link to https://www.colorado.gov/
- Updated the licensing string displayed on the bottom of admin pages to reflect what's listed in the [Github repo](https://github.com/dfpc-coe/CloudTAK/blob/main/LICENSE).

Corrected typo in the footer

---

api/web/src/components/Login.vue

- Added missing "an" in "Don't have an account yet?"
- Pointed to existing sign-up page instead of dev e-mail

Grammar fix and pointer to sign-up page

---

api/routes/connection-layer-ephemeral.ts
api/routes/connection-layer.ts
api/test/fixtures/get_schema.json

In the case of an Environment change in the layer that changes the means of authentication, the ephemeral store can potentially have old but unexpired tokens that appear valid.
This reduces the chance of this problem by invalidating the ephemeral cache when an environment is changed.

Cache Invalidation

---

api/web/src/components/CloudTAK/FeatView.vue

On mobile the Feature sidebar would overflow and on desktop it would result in results being cutoff without scroll
Closes: https://github.com/dfpc-coe/CloudTAK/issues/556

feature scroll

---

api/lib/control/tilejson.ts
api/lib/models/Layer.ts
api/routes/basemap.ts
api/routes/connection-layer-cot.ts
api/routes/connection-layer.ts
api/routes/internal.ts
api/routes/profile-overlays.ts
api/web/src/components/Admin/AdminConnections.vue
api/web/src/components/Admin/AdminLayers.vue
api/web/src/components/CloudTAK/Menu/MenuFiles.vue
api/web/src/components/Layer/LayerIncomingStyles.vue
api/web/src/components/Layer/utils/StatusDot.vue
api/web/src/derived-types.d.ts

- :rocket: Show Connection name in Admin Layer List
- :rocket: Show incoming/outgoing/bidirectional status in Admin Layer List
- :rocket: Remove `cron` header by default in Admin Layer List as that is specific to incoming layers
- :bug: Fix filtering bug when JSONata query is set to delete data
- :rocket: Migrate AdminConnection Component to `setup`
- - :rocket: Migrate AdminLayer Component to `setup`

JSONata Query Fix

---

api/lib/aws/lambda.ts
api/routes/connection-layer.ts

This PR introduces a new Lambda ETL Event of either `environment:incoming` OR `environment:outgoing` that will be fired any time a Layer's Incoming or Outgoing environment is changed.
This will directly support the ability to dynamically specify new columns in AGOL sources and have the ETL dynamically provision them on the ESRI Server.
ETLs will need to update to the simultaneously release: https://github.com/dfpc-coe/etl-base/releases/tag/v9.9.0
cc/ @adrienhoff @bs-in-co

Lambda Invocaion Type

---

api/web/src/base/cot.ts
api/web/src/components/CloudTAK/CoTView.vue

Vue3 uses a proxy when wrapped by `ref` or `reactive` to handle updating state in the DOM when underlying updates are made to the wrapped object. Since this wrapping takes place AFTER class construction, internal updates were not properly triggering DOM updates.
This PR makes underlying updates a manual but necessary function call to ensure that the class is wrapped by Proxy

Fix Reactivity

---

api/web/src/components/CloudTAK/util/FloatingVideo.vue
api/web/src/components/Layer/LayerDeployment.vue
api/web/src/components/Layer/LayerIncomingConfig.vue

The "Play" button for a layer ETL only invokes the function that handles scheduled runs on incoming ETLs. As such it no longer makes sense to show this on the top level deployment card which can support unsupported ETLS ie: webhooks or outgoing where the "play" button would perform no action.
This PR moves the play button to the Incoming Config page and only shows it if incoming schedules are configured.
Closes: https://github.com/dfpc-coe/CloudTAK/issues/646

Move Invoke to incoming

---

api/web/package-lock.json
api/web/src/components/Layer/utils/Schema.vue

Adds the following support to the Layer Environment Editor
- Apply defaults to `integer` type if available
- Apply defaults to `number` type if available
- Treat number as a numeric input type
- Treat integer as a numeric input type with `step: 1`

Schema support for numeric types

---

api/web/package-lock.json
api/web/package.json
api/web/src/App.vue
api/web/src/base/utils/styles.ts
api/web/src/components/CloudTAK/DrawTools.vue
api/web/src/components/CloudTAK/LostPersonBehaviorInput.vue
api/web/src/components/CloudTAK/Map.vue
api/web/src/components/CloudTAK/util/FloatingVideo.vue
api/web/src/pages/docs/App.vue

This pull request introduces several updates to the project, including dependency upgrades, new features for drawing tools, and improvements to filtering logic in styles. The most significant changes are the addition of new drawing tools, the refactoring of the `Map.vue` component to use a dedicated `DrawTools` component, and updates to filtering logic for map layers.
* Upgraded the project version in `package-lock.json` from `10.16.0` to `10.18.0`.
* Added `@turf/ellipse` as a new dependency in `package.json` and `package-lock.json`. [[1]](diffhunk://#diff-60823d2f4576e1ac0c836baf2c06398d8645fe7a0511c4bdb74a0970c5588c3fR30) [[2]](diffhunk://#diff-e57688cc8ba1f7393d198a2ffc1dfb2bf81fb847c855aa3ec6fd395b1f8589b2R23)
* Updated `@tak-ps/node-cot` dependency from version `13.3.0` to `13.4.0` …

Draw Tool Components

---

api/Dockerfile

This PR fixes #740 and addresses three issues with the current data download approach in `api/Dockerfile`:
**Problems solved:**
1. **Inefficient two-step process** - Eliminates unnecessary `git clone` + `mv` operations that create extra Docker layers
2. **Hardcoded data source** - Allows organizations to use custom CloudTAK data repositories
3. **Public repository limitation** - Enables local ZIP files for data containing API keys or proprietary content
**Changes:**
- Replace `git clone` with configurable ZIP download approach
- Add `DATA_SOURCE_URL` and `USE_LOCAL_ZIP` build arguments for flexibility
- Move data download after `npm run build` to eliminate the move operation
- Add required tools: `wget`, `unzip`
- Support local ZIP files for private/proprietary data
**Backward …

Improve Dockerfile data download efficiency and flexibility

---

api/web/src/components/Layer/LayerIncomingStyles.vue

- Removed `bg-white` class from card header elements that was conflicting with dark theme styling
- Affects sticky card headers in layer styling components
The `bg-white` class was forcing white backgrounds on card headers, which interferes with the new dark design implementation. Removing this allows the dark theme to properly style these elements.
**Before**
**After**

Remove bg-white from card headers for dark theme support

---

api/lib/style.ts
api/test/style.test.ts

CloudTAK templates needed better data formatting capabilities:
- VMS data from [Waka Kotahi](https://www.journeys.nzta.govt.nz/assets/map-data-cache/vms.json) contains encoded markers (`[nl]`, `[np]`) that clutter display
- Numeric data - e.g. for earthquake magnitude data from GeoNet NZ - has excessive decimal precision making UI hard to read
Added two new Handlebars helpers:
- Performs literal string replacement using `replaceAll()`
- Supports chaining for multiple replacements
- No regex escaping required
- Formats numbers to specified decimal places
- Defaults to 2 decimal places with configurable precision
- Handles null/undefined/NaN values gracefully
```javascript
// Text cleanup
{
"remarks": "{{replace (replace currentMessage '[nl]' ' ') '[np]' ' '}}"
}
// Number formatting
{ …
```

Add Template Helpers for Text and Number Formatting

---

api/web/src/base/utils/styles.ts

The current default circle marker radius of 4 pixels makes point features difficult to see and interact with on the map, especially at lower zoom levels or on high-DPI displays.
- Increase default `circle-radius` from 4 to 8 pixels in the circle layer specification
- Maintains all other default properties (green color, full opacity)
- Preserves ability for features to override size via `marker-radius` property
```typescript
// Before
'circle-radius': ["number", ["get", "marker-radius"], 4],
// After  
'circle-radius': ["number", ["get", "marker-radius"], 8],
```
* **Improved Visibility:** Larger markers are easier to spot on the map
* **Better UX:** Increased click target size improves user interaction
* **Accessibility:** Better visibility for users with visual impairments
* …

Increase Default Circle Marker Size for Better Visibility

---

api/lib/sinks.ts

Several messages failed to be delivered to an outgoing ETL due to the length of the given `uid`. To ensure this does not happen in the future, the MessageGroupID is now truncated to the max 128 characters.

Sink Error

---

api/routes/connection-layer.ts
api/test/connection-layer.srv.test.ts

The default memory is often a bottleneck for ETL integrations. The DB default was updated to 256 some time ago however the API default was never updated to match.

Update Default Memory to 256

---

api/web/src/base/cot.ts
api/web/src/components/CloudTAK/CoTView.vue
api/web/src/components/CloudTAK/Map.vue
api/web/src/stores/map.ts
api/web/src/stores/modules/draw.ts
api/web/src/workers/atlas-database.ts
api/web/src/workers/atlas-profile.ts

Vector Tiles IDs only support integers however MapLibre allows string types per the GeoJSON spec but under the hood simply runs a parseInt call which resulted in hash collision.
As part of this work the CoTs now use a vectorId function to calculate an unsigned integer for each function.
The Diff code however was conflicting with this use as it still uses a string in some operations.

Map Diff Updates

---

bin/build.js
cloudformation/lib/api.js
cloudformation/lib/events.js

Make ECS Task Definition CPU/Memory a configurable paramters to allow us to downsize CloudTAK size (and costs!) in a staging environment.

Set CPU/Memory Size as Parameter

---

api/routes/basemap.ts
api/web/src/components/CloudTAK/Menu/MenuBasemaps.vue

- Expands the `type` query parameter to allow querying for multiple types in a single query
- Only queries for `raster` and `vector` in basemap UI
Closes: https://github.com/dfpc-coe/CloudTAK/issues/925

Filter By Basemap Type

---

api/routes/ldap.ts

CA Chain was not being returned in a PUT Request to update a machine user

Return Chain in PUT

---

api/web/src/components/CloudTAK/Menu/MenuRoutes.vue
api/web/src/components/CloudTAK/Menu/MenuRoutesNew.vue

- :bug: Route Creation didn't supply authorship tag resulting in then not being automatically added to an active mission
- :rocket: Show Routes that are part of a Data Sync in the Routes List Menu

Mission Routes

---

cloudformation/lib/pmtiles.js
docker-compose.yml
tasks/pmtiles/src/index.ts
tasks/pmtiles/src/lib/tiles.ts

Use consistent Env Var names for ease of updating when deploying in a docker-compose context
@chriselsen Note: the CDK stack will need to update to use the now consistent `PMTILES_URL`  env var instead of `APIROOT`

Fix Consistent Env Vars
