api/schema/req.body.CreateLayer.json, api/schema/req.body.PatchLayer.json, api/schema/util/layerdata.json, api/web/package-lock.json, api/web/src/App.vue, api/web/src/components/Connection.vue, api/web/src/components/Connection/Layers.vue, api/web/src/components/ConnectionEdit.vue, api/web/src/components/Connections.vue, api/web/src/components/Home.vue, api/web/src/components/Layer.vue, api/web/src/components/LayerEdit.vue, api/web/src/components/Layers.vue, api/web/src/components/cards/Connections.vue, api/web/src/components/cards/Layers.vue, api/web/src/components/util/Asset.vue, api/web/src/components/util/ConnectionSelect.vue, api/web/src/components/util/LayerData.vue, api/web/src/components/util/Styles.vue, api/web/src/components/util/UploadInline.vue, api/web/src/components/util/UploadP12.vue
Finalize the ability to upload to File Layers
=> File Uploads

api/package-lock.json, api/package.json, api/routes/layer.js, api/schema/layers/styles.json, api/test/flight.js, api/test/submit.js, api/web/package-lock.json, api/web/src/components/Connection/Events.vue, api/web/src/components/Layer/Styles.vue
Reverse engineer the ATAK Style Spec by creating varying CoT messages in the client and broadcasting
| Value | Values |
| --- | --- | 
| `styleWeight` | 0 -> 6 atak (in pixels) |
__Min Value__
```json
{"event":{"_attributes":{"version":"2.0","uid":"linestring","type":"u-d-f","how":"h-e","time":"2022-12-26T17:01:55Z","start":"2022-12-26T17:01:55Z","stale":"2022-12-27T17:01:55Z"},"point":{"_attributes":{"lat":39.9854387,"lon":-105.3813822,"hae":2414.421,"ce":9999999,"le":9999999}},"detail":{"contact":{"_attributes":{"callsign":"UNKNOWN"}},"link":[{"_attributes":{"point":"39.8520354,-105.5868627"}},{"_attributes":{"point":"40.0224484,-105.4526714"}},{"_attributes":{"point":"40.0818323,-105.1046126"}}],"archive":{},"labels_on":{"_attributes":{"value":"false"}},"color":{"_attributes":{"value":" …
```
=> Style testing

.deploy, api/Dockerfile, api/lib/tak.js, cloudformation/etl.template.js, cloudformation/lib/api.js, cloudformation/lib/batch.js, cloudformation/lib/db.js, cloudformation/lib/s3.js
Get repo ready for deployment onto AWS
=> Deploy Preparation

api/doc/api.js, api/index.js, api/lib/auth.js, api/lib/config.js, api/package-lock.json, api/package.json, api/routes/asset.js, api/routes/connection.js, api/routes/layer.js, api/routes/mission-data.js, api/test/fixtures/get_schema.json, api/web/src/App.vue, api/web/src/components/Login.vue, api/web/src/main.js, api/web/src/std.js, cloudformation/etl.template.js, cloudformation/lib/api.js
Add Login Blueprint for handling authentication to ETL platform
=> Login Blueprint

api/migrations/20230114043057_unique.js
Closes: https://github.com/tak-ps/etl/issues/14
Closes: https://github.com/tak-ps/etl/issues/13
=> Add Unique Indexes

api/package-lock.json, api/package.json
Closes: https://github.com/tak-ps/etl/issues/25
=> node-cot@2.8

.gitignore, api/doc/api.js, api/index.js, api/lib/cacher.js, api/lib/config.js, api/nginx.conf, api/package.json, api/routes/task.js, api/schema/res.ListTaskVersions.json, api/test/fixtures/get_schema.json, api/test/flight.js, api/web/src/App.vue, api/web/src/components/Layer/LayerData.vue, cloudformation/lib/api.js, cloudformation/lib/db.js
Allow looking up versions for a specific task
Closes: https://github.com/tak-ps/etl/issues/27
=> Task Version API

api/lib/aws/alarm.js, api/routes/connection.js, api/routes/layer.js, api/schema/res.Layer.json, api/schema/res.ListConnections.json, api/schema/res.ListLayers.json, api/web/package-lock.json, api/web/package.json, api/web/src/components/Icons.vue, api/web/src/components/Layer.vue, api/web/src/components/Layer/Status.vue, api/web/src/components/Layers.vue, api/web/src/components/cards/Connections.vue, api/web/src/components/cards/Layers.vue
Now that all of our tasks have monitoring and alarms, wire up the status check icons on layers to represent that state of these alarms
=> Live Layer Status

api/doc/api.js, api/lib/aws/logs.js, api/lib/style.js, api/routes/task.js, api/schema/res.TaskLogs.json, api/test/fixtures/get_schema.json, api/web/src/components/Layer/LayerTask.vue, cloudformation/lib/api.js
Add the ability for admins to view logs specific to a given layer. This can help non-aws (but admin COE) users see logs relating to the layer code if an environment variable or config option is misconfigured.
=> Layer Logs

api/lib/aws/dynamo.ts, api/routes/layer.ts, api/schema/req.body.CreateLayer.json, api/schema/req.body.PatchLayer.json, api/schema/res.Layer.json, api/web/src/components/Layer.vue, api/web/src/components/LayerEdit.vue, cloudformation/lib/dynamo.js
Automatically clean out database features +24 hours after their expiry or if no expiry tag is set, 24hrs after ingestion.
=> DynamoDB TimeToLive

api/web/src/components/Layer/LayerData.vue, api/web/src/components/Layer/LayerEnvironent.vue, api/web/src/components/Layer/TaskModal.vue
- Automatically navigate to the versions list in the TaskModal if the task has already been selected
- Show the refresh icon in edit mode
- Allow the new version to be clickable and populate the task field.
=> Task Updates

.deploy, .github/workflows/ecr_api.yml, api/lib/aws/lambda.ts, api/package-lock.json, api/web/package-lock.json, api/web/src/components/Layer/LayerData.vue, api/web/src/components/Layer/LayerEnvironent.vue, api/web/src/components/Layer/Schema.vue, api/web/src/components/LayerEdit.vue, api/web/src/components/util/Alert.vue, api/web/src/components/util/UploadCSV.vue, cloudformation/lib/api.js, cloudformation/lib/batch.js, cloudformation/lib/db.js, cloudformation/lib/kms.js, package-lock.json
Use the dynamo history logs to be able to populate requested fields in the ETL Lambda provided schema.
=> Custom Selector

api/doc/api.js, api/lib/aws/dynamo.ts, api/package-lock.json, api/routes/layer-query.ts, api/schema/res.LayerQueryFeature.json, api/test/fixtures/get_schema.json, api/tsconfig.json, api/web/src/components/LayerQuery.vue, api/web/src/components/LayerQueryFeature.vue, api/web/src/main.js
Add API endpoints necessary to query Dynamo Feature Store by Id.
=> Add Query Feature API

api/index.ts, api/lib/config.ts, api/lib/tak-pool.ts, api/lib/tak.ts, api/routes/connection.ts, api/routes/layer.ts, api/routes/server.ts, api/schema/req.body.PatchConnection.json, api/web/src/components/Connection/Status.vue, api/web/src/components/ConnectionEdit.vue
If server settings are changed while the server is running via the Admin UI or Server API, the config.server value is updated and subsequent connections will use the updated server information.
However existing connections are not notified of the new settings in any way, and continue to push data to the old server configuration that has been removed from the server.
This PR adds a connection refresh function which is called on server config changes and forces a full regen of all connections.
=> Server Refresh

api/lib/style.ts, api/lib/tak.ts, api/package-lock.json, api/package.json, package-lock.json, package.json
Update node-cot to support Course & Speed parsing
=> Course & Speed

api/package-lock.json, api/routes/data-asset.ts, api/web/package-lock.json, api/web/src/components/BaseMap/Location.vue, api/web/src/components/Data/Location.vue, tasks/pmtiles/package-lock.json, tasks/pmtiles/package.json, tasks/pmtiles/src/index.ts
Closes: https://github.com/tak-ps/etl/issues/57
Closes: https://github.com/tak-ps/etl/issues/60
=> Add JWT Auth Check

api/package.json, api/routes/layer.ts
Increase the buffer size for CoT messages coming in via the CoT submission endpoint.
Partially fix for: https://github.com/tak-ps/etl/issues/69
=> Increase Buffer Size On CoT Endpoint

api/lib/aws/metric.ts, api/lib/sinks.ts, api/migrations/20230723153253_sink-logging.js, api/schema/connection_sinks.json, api/schema/connection_sinks/logging.json, api/schema/req.body.CreateConnectionSink.json, api/schema/req.body.PatchConnectionSink.json, api/schema/res.ConnectionSink.json, api/web/src/components/ConnectionSink.vue, api/web/src/components/ConnectionSinkEdit.vue, api/web/src/components/util/EsriPortal.vue, api/web/src/components/util/EsriServer.vue, tasks/hooks/src/index.ts
- Signiticant Improvements to Read-Only ESRI Component
- Default to disabling logging for sinks to save costs
- Add `stats` view to Sinks to surface Delivery stats (hidden if logging is disabled)
=> Optional Logging

api/lib/aws/metric.ts, api/routes/connection.ts, api/web/src/components/Admin.vue, api/web/src/components/Connection.vue, api/web/src/components/Connection/Chart.vue, api/web/src/components/Connection/Events.vue, api/web/src/components/Connection/Layers.vue, api/web/src/components/Connection/Sinks.vue
=> Add Connection Throughput Chart

api/package-lock.json, api/package.json, api/routes/task.ts, api/schema/req.query.TaskSchema.json, api/web/src/components/Layer.vue, api/web/src/components/Layer/LayerSchema.vue, api/web/src/components/LayerEdit.vue
Allow populating the Schema by calling the `schema:output` event on a given ETL.
=> Output Schema

api/index.ts, api/lib/enums.ts, api/lib/schema.ts, api/lib/types.ts, api/migrations/0029_deep_sir_ram.sql, api/migrations/0030_wide_bromley.sql, api/migrations/meta/0029_snapshot.json, api/migrations/meta/0030_snapshot.json, api/migrations/meta/_journal.json, api/package-lock.json, api/package.json, api/routes/profile.ts, api/test/test, api/tsconfig.json, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/Settings.vue, api/web/src/components/CloudTAK/util/Speed.vue, api/web/src/stores/connection.ts, api/web/src/stores/cots.ts, api/web/src/stores/map.ts
=> Display Settings

api/lib/auth.ts, api/lib/esri.ts, api/lib/provider.ts, api/lib/tak-api.ts, api/package-lock.json
- **Grayed out opts**
- **Setup Default Values**
- **Fix lints**
- **DB Migration**
- **Add Profile Enums**
- **Add Enums**
- **Add Display Units**
- **DB Migration**
- **Migrate to tsx**
- **Update TSConfig**
- **Update Index**
- **Update Internal**
- **Update Migration**
- **Update Migration**
- **Use Filter Val**
- **Include unit in speed**
- **Add Default Speed**
- **Add staleout**
- **ProfileStore**
- **async import**
- **Remove NodeMon**
- **Test Cond**
- **Flip Cond**
- **Fix tests**
- **Fix Ping Wave of Death**
- **InstanceOf**
- **Check Name**
- **Migrate to name**
=> Restart COT Surge

api/lib/api/package.ts, api/lib/tak-api.ts, api/routes/icons.ts, api/routes/marti-package.ts, api/test/fixtures/get_schema.json, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/Packages.vue, api/web/src/main.js
Add support for Data Package Listing
=> Data Package Listing

api/lib/api/mission.ts, api/lib/api/package.ts, api/routes/marti-package.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Package.vue, api/web/src/components/CloudTAK/Menu/Packages.vue, api/web/src/main.js
- **Add Package get**
- **Add Package route**
- **Complete Mission Schema**
- **Allow Downloading**
=> data package

api/package-lock.json, api/routes/marti-package.ts, api/routes/task.ts, api/test/fixtures/get_schema.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/util/SelectFeats.vue
- **Add new put package call**
- **Update Deps**
- **Cancel** Stack Deployment
=> Data Package PUT

api/web/src/stores/map.ts
=> Better Labels

api/web/src/components/Layer/LayerDeployment.vue
=> Single Page Deployment

CHANGELOG.md, api/lib/esri.ts, tasks/events/.eslintrc.json, tasks/events/eslint.config.js, tasks/events/package-lock.json, tasks/events/package.json, tasks/events/src/api.ts, tasks/events/src/index.ts
- **Update Events**
- **Smarter ESRI Parsing**
=> ESRI Parsing & Events

CHANGELOG.md, api/web/src/components/Connection/ConnectionGroups.vue, api/web/src/components/util/EsriServer.vue
=> Surface Esri Server Type

api/web/src/components/CloudTAK/CoTView.vue
Automatically convert `http(s)` text to a link
=> Add Automatic Lints

api/lib/connection-pool.ts, api/package-lock.json, package-lock.json
Add support for parsing the `ackresponse` portion of a CoT Message
=> ACK Response

api/lib/style.ts, api/package-lock.json, api/routes/layer.ts, api/web/src/components/Layer/LayerStyles.vue, api/web/src/components/Layer/utils/StyleSingle.vue, api/web/src/components/Layer/utils/StyleTemplate.vue
=> Styling Editor

api/web/src/components/Admin.vue, api/web/src/components/Admin/AdminConnections.vue, api/web/src/components/Admin/AdminLayers.vue, api/web/src/main.js
=> Layer id and conns

api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/FeatView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/QueryView.vue, api/web/src/components/CloudTAK/util/Coordinate.vue
Evening hack project to allow efficient manual entry of coordinates, inspired by beers with ben entering cave coordinates last night  and how painful it is in some competing cloud based geospatial tools.
=> Coordinate Entry

api/web/src/components/CloudTAK/util/CoTStyle.vue, api/web/src/components/util/IconSelect.vue
=> Fix Icon Size

CHANGELOG.md, api/lib/auth.ts, api/lib/config.ts, api/lib/external.ts, api/lib/provider.ts, api/lib/schema.ts, api/lib/style.ts, api/migrations/0036_solid_goliath.sql, api/migrations/meta/0036_snapshot.json, api/migrations/meta/_journal.json, api/package.json, api/routes/agency.ts, api/routes/connection.ts, api/routes/login.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/Connection.vue, api/web/src/components/Connection/AgencyBadge.vue, api/web/src/components/ConnectionEdit.vue, api/web/src/components/Connections.vue, api/web/src/components/util/AgencySelect.vue, cloudformation/lib/hooks.js, tasks/hooks/src/adaptors/arcgis.ts
- **Sketch out Agency List**
- **Wire up external provider**
- **Add External**
- **Add ID & Name**
- **Setup Agency List/Get & use proxy**
- **Update Agency Lints**
- **Setup Profile ID & Name**
- **Add user.id**
- **Types**
- **Lint Fixes**
- **As_User**
- **DB Migration**
- **Get from profile**
- **Setup Agency Dropdown**
- **Update Agency APIs**
- **Update Style Test**
- **Add Agency/Server Diff**
- **Add Connection Agency Badge**
- **Allow Removing Agency**
- **Switch to proxy call for Agencies**
- **Update CHANGELOG**
=> Agency Select

api/web/package-lock.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/cots.ts
We regenerate the current on-screen CoT layer every 0.5 seconds. This is generally a very performant operation, however with large datasets can deliver a small amount of lag due to the amount of data being regenerated.
This PR significantly increases performance of map rendering by differentiating the store of existing map objects that are rendered on the screen from yet to be added/removed/updated objects. Upon the updateCOT call every 0.5 seconds it then checks the status of the pending queue and skips updating the screen if no pending changes are present. If pending changes ARE present, it then only updates the vector tiles necessary for those particular features - avoiding a full refresh.
=> Partial Update

api/lib/aws/ec2.ts, api/lib/aws/ecs-video.ts, api/lib/types.ts, api/package-lock.json, api/package.json, api/routes/videos.ts, api/web/src/components/Admin.vue, api/web/src/components/Admin/AdminConnections.vue, api/web/src/components/Admin/AdminLayers.vue, api/web/src/components/Admin/AdminTasks.vue, api/web/src/components/Admin/AdminUsers.vue, api/web/src/components/Admin/AdminVideo.vue, api/web/src/components/Admin/AdminVideos.vue, api/web/src/components/Connection.vue, api/web/src/components/Connections.vue, api/web/src/main.js, cloudformation/lib/api.js
- **Video Object**
- **Update Video Page**
- **Add Tasks List**
- **Add Video Server List & Info**
-
=> Video Server Management

api/lib/aws/ecs-video.ts, api/lib/types.ts, api/routes/videos.ts, api/test/fixtures/get_schema.json, api/web/src/components/Admin/AdminVideo.vue, api/web/src/components/Admin/AdminVideos.vue, api/web/src/components/util/Status.vue, cloudformation/lib/api.js
- **Add Ability to stop task**
- **Add Backbutton**
- **Add Deprovisioning**
- **Add Ability to delete Media Server Task**
=> Video Server Deletion

api/lib/types.ts, api/routes/profile-features.ts, api/web/src/App.vue, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/map.ts
Cleaner implementation of the work that was started in https://github.com/dfpc-coe/CloudTAK/pull/165
=> Multi Feature Select

CHANGELOG.md, api/lib/api/mission.ts, api/lib/limits.ts, api/package-lock.json, api/routes/connection.ts, api/routes/marti-mission.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Channels.vue, api/web/src/components/CloudTAK/Menu/Mission.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue, api/web/src/components/Connection/ConnectionGroups.vue
Lookup current Mission Permissions before performing a Mission Sync operation to allow giving a human readable error as to why an action may not have worked instead of a machine readable error from the TAK Server
=> Mission Permissions

api/lib/data-mission.ts, api/package-lock.json, api/routes/connection-layer-cot.ts, api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue
Submit data with proper `path` values
=> Layer Content

api/lib/data-mission.ts, api/routes/marti-mission-layers.ts, api/test/fixtures/get_schema.json, api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionCreate.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerCreate.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerEdit.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionTimeline.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionUsers.vue
- **Add Enter to Create Mission Layer**
- **Support renaming layers**
=> Rename Mission Sync Layers

api/package-lock.json, api/package.json
Add support for (de)serializing GeoFence CoTs
=> GeoFence CoTs

api/lib/api/mission-layer.ts, api/routes/connection-layer-cot.ts
- :rocket: Helper functions to get single Layer from Mission Sync Layers
- :rocket: Helper function to get `latestFeats` from single Layer
- :rocket: Perform Mission Diff on Layers
=> Diff on MissionLayer

api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue
=> CoTs in Mission Layers

CHANGELOG.md, api/package-lock.json, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/App.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/Profile/ProfileVideos.vue, api/web/src/components/Profile/VideoLeaseModal.vue
- **Add Stroke=1 for rect**
- **Target Cursor**
=> target cursor

api/routes/profile-features.ts, api/test/fixtures/get_schema.json, api/web/src/components/Layer/utils/TaskModal.vue, tasks/data/package-lock.json, tasks/events/package-lock.json, tasks/events/package.json, tasks/events/src/api.ts, tasks/events/src/import.ts, tasks/hooks/package-lock.json
DataPackages currently push contents to the database but don't have the ability to broadcast them in any meaningful way.
=> Broadcast on Ingest

api/web/src/components/CloudTAK/Menu/Package.vue, api/web/src/components/CloudTAK/util/Share.vue
=> Pin Share to bottom

api/index.ts, api/lib/connection-web.ts, api/lib/external.ts, api/package-lock.json, api/package.json, api/routes/basemap.ts, api/routes/ldap.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/FeatView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/Basemaps.vue, api/web/src/components/CloudTAK/Menu/Channels.vue, api/web/src/components/CloudTAK/Menu/Connections.vue, api/web/src/components/CloudTAK/Menu/Contacts.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue, api/web/src/components/CloudTAK/Menu/Missions.vue, api/web/src/components/CloudTAK/Menu/Overlays.vue, api/web/src/components/CloudTAK/Menu/Package.vue, api/web/src/components/CloudTAK/Menu/Packages.vue, api/web/src/components/CloudTAK/QueryView.vue, api/web/src/components/Connection/AgencyBadge.vue, api/web/src/components/Connection/CertificateMachineUser.vue, api/web/src/components/Connections.vue, api/web/src/components/Login.vue, api/web/src/main.js, api/web/src/stores/map.ts
- **Add Pinned Menu**
- **Tooltips on Menu**
- **Smaller Icons**
- **Remove double component**
- **Add Sidepanel**
- **Update Menu**
- **Fix Menu**
- **Setup Connection Status**
- **Add Filter**
- **Smarter Tooltips on menu**
- **Fix Placement**
- **Add Connections Menu Page**
- **Connections List**
- **Update Web Deps**
- **Use RDN for channels**
- **Interpolate Line/Poly texts on zoom level to match pts**
=> Pinned Menu

api/lib/esri.ts, api/routes/connection-task.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/Basemaps.vue, api/web/src/components/CloudTAK/Menu/Channels.vue, api/web/src/components/CloudTAK/Menu/Connections.vue, api/web/src/components/CloudTAK/Menu/Contacts.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue, api/web/src/components/CloudTAK/Menu/Missions.vue, api/web/src/components/CloudTAK/Menu/Overlays.vue, api/web/src/components/CloudTAK/Menu/Packages.vue, api/web/src/components/CloudTAK/util/Contact.vue, api/web/src/components/CloudTAK/util/ContactPuck.vue, api/web/src/components/CloudTAK/util/Share.vue, api/web/src/components/Layer/LayerEnvironment.vue, api/web/src/components/LayerEdit.vue, api/web/src/stores/cots.ts
=> Contact Filter

CHANGELOG.md, api/lib/geocode.ts, api/lib/models/Setting.ts, api/routes/internal.ts, api/routes/search.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/package.json, api/web/src/components/CloudTAK/Map.vue, package-lock.json, package.json
=> Forward Geocode

api/web/package-lock.json, api/web/src/components/Layer/utils/Schema.vue
- Show `description` and `required` props from JSON Schema in Layer UI
=> Description & Required

api/lib/style.ts, api/package-lock.json, api/web/src/components/CloudTAK/Menu/Overlays.vue, api/web/src/components/Layer/utils/StyleSingle.vue
- **Hide CoT tree on Missions**
- **Add Type to style**
- **Add Type**
=> Point Type Override

api/lib/api/package.ts, api/package-lock.json, api/web/package-lock.json, api/web/src/components/CloudTAK/CoordInput.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/Overlays/TreeCots.vue, api/web/src/components/CloudTAK/Menu/Packages.vue, api/web/src/components/CloudTAK/util/Coordinate.vue, api/web/src/components/CloudTAK/util/Feature.vue, api/web/src/stores/cots.ts
- **List Features**
- **Fix recursive component in CoordInput**
=> COT Tree Improvements

api/package-lock.json, api/web/package-lock.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/map.ts
- **TerraDraw ID Strategy**
- **Add TerraDraw improvements**
- **Coordinate Precision**
=> Point Geom Coords on Edit

api/lib/style.ts, api/package-lock.json, api/package.json, api/routes/connection-layer-cot.ts
Submitting 5k+ features in one payload would cause the server to OOM and crash.
The following were the source of the memory issues
- Lack of cached handlebar templates resulting in template compilation on every feature
- Use of `check-geojson` double serial/desieralize
The following mitigation strategies were performed
- Remove use of `check-geojson` in favour of `InputFeature` schema definition from node-cot
- Introduction of a cache system for reusing compiled handlebar templates within a single feature collection payload
=> CoT Improvements

api/lib/style.ts, api/web/src/components/Layer/utils/StyleSingle.vue
- **Add Toggles for Global Properties**
- **Add enable script**
- **Set Fill**
- **Setup Enabler**
- **Add enabled watcher**
=> ID Override

api/package-lock.json, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/util/Elevation.vue
=> Elevation CoTView

api/lib/api/files.ts, api/package-lock.json, api/routes/attachments.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/util/Attachments.vue, api/web/src/stores/connection.ts, tasks/events/package-lock.json, tasks/events/package.json, tasks/events/src/import.ts, tasks/events/src/index.ts, tasks/pmtiles/package-lock.json
[Screencast from 2024-08-05 16-21-48.webm](https://github.com/user-attachments/assets/6a463045-6332-4c22-86d7-3ffc57c3e614)
=> Attachments

api/lib/control/attachment.ts, api/package-lock.json, api/package.json, api/routes/attachments.ts, api/test/fixtures/get_schema.json, api/web/index.html, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/Basemaps.vue, api/web/src/components/CloudTAK/util/Attachments.vue, api/web/src/components/CloudTAK/util/MultipleSelect.vue, api/web/src/components/util/Upload.vue
Add endpoint for uploading attachments to a given CoT
=> Attachment Attach

api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Overlays.vue, api/web/src/components/CloudTAK/Menu/Overlays/TreeMission.vue, api/web/src/components/CloudTAK/util/Feature.vue, package-lock.json, package.json
Add mission CoTs in Overlay explorer
A subsequent PR will explore an efficient way for supporting Mission Layers
=> Mission Tree

api/web/package-lock.json, api/web/package.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/util/Attachments.vue, api/web/src/components/CloudTAK/util/Feature.vue, api/web/src/components/Login.vue, api/web/src/stores/cots/cot.ts
Zooming was usually done via the centroid as it was the property that would always be present. 
This PR now conditionally zooms via a fitBounds call so that polygons are fit within the screen when clicked instead of zoomed into their center. This is done via the new rendering class with the addition of a universal `bounds()` fn on all cots
=> Feat Bounds

CHANGELOG.md, api/lib/api/mission.ts, api/routes/marti-mission.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/Basemaps.vue, api/web/src/components/CloudTAK/Menu/Channels.vue, api/web/src/components/CloudTAK/Menu/Contacts.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionCreate.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue, api/web/src/components/CloudTAK/Menu/Missions.vue, api/web/src/components/CloudTAK/Menu/Packages.vue, api/web/src/components/util/GroupSelect.vue, api/web/src/components/util/GroupSelectModal.vue
- :rocket: Padding above filter boxes in menu
- :bug: Fix scrolling in CoTView raw mode
- :rocket: Fix margins/padding in Mission Sync logs
- :rocket: **Breaking** Create Mission Syncs with POST request, simplifying the internal code
- :rocket: Use unified GroupSelect, adding search/filtering
- :rocket: Show subscribed missions at top of Missions Menu
=> MissionSync Papercuts

api/lib/api/mission.ts, api/package-lock.json, api/routes/connection-layer-cot.ts, api/routes/types.ts, api/web/package-lock.json, api/web/package.json
The DataSync diff code in CoT submission currently uses an API Call for detaching CoT contents. 
This PR tried to make this more efficient by using the `t-x-d-d` delete CoT to streamline deletes by submission via the CoT stream.
=> Force Delete COT [WIP]

api/package-lock.json, api/routes/connection-layer-cot.ts, api/web/package-lock.json
Turns out the MissionAPI doesn't internally support `t-x-d-d` and results in strange behavior on ATAK clients. This temporarily rolls back use of `t-x-d-d` with Mission Sync until support is added for this behavior in TAK@5.3
=> DetachContents

api/routes/ldap.ts, api/web/src/components/Connection/CertificateMachineUser.vue
Ensure at least one channel is selected when a machine user is created
=> Machine User Creation Papercuts

api/lib/control/video-service.ts, api/routes/video-lease.ts, api/web/package-lock.json, api/web/src/components/Admin/AdminUser.vue, api/web/src/components/Admin/VideoConfig.vue
- **Add Path API Creation**
- **Create Lease**
- **Custom values for some User props**
=> Video Path API

api/lib/control/video-service.ts, api/lib/schema.ts, api/migrations/0056_round_galactus.sql, api/migrations/meta/0056_snapshot.json, api/migrations/meta/_journal.json, api/package-lock.json, api/routes/video-lease.ts, api/test/fixtures/get_schema.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/Import.vue, api/web/src/components/CloudTAK/Menu/Videos.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/Coordinate.vue, api/web/src/components/CloudTAK/util/CopyField.vue, api/web/src/components/CloudTAK/util/Course.vue, api/web/src/components/CloudTAK/util/Elevation.vue, api/web/src/components/CloudTAK/util/Speed.vue, cloudformation/lib/db.js
Closing the loop on Video Lease APIs/UIs
=> Video Paths

api/lib/api/mission-layer.ts, api/lib/api/mission.ts
Closes: https://github.com/dfpc-coe/CloudTAK/issues/276
=> MissionGuid

api/lib/api/mission-layer.ts, api/lib/api/mission.ts, api/package-lock.json, api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/overlays/base.ts
Allow showing Mission CoTs via CoTview instead of the generic Feature View
=> MissionView

api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue
Implement Austin's wizard graphics
=> VideoWizard

api/web/package-lock.json, api/web/package.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/map.ts
Ref: https://github.com/JamesLMilner/terra-draw/pull/306
=> Angled Rectangle Mode

tasks/hooks/package-lock.json, tasks/hooks/package.json
Small dependency updates to squash the fast-xml DDoS vuln which while not relevant as the XML is trusted in this case, will make an alert go away
=> Update Hook Code

api/lib/models/Layer.ts, api/routes/internal.ts, api/web/package-lock.json, api/web/src/components/Admin/AdminLayers.vue
Give admin's the ability to filter layers by Task Type
=> Filter Layers

api/web/src/components/Admin/AdminLayers.vue, api/web/src/components/CloudTAK/CoordInput.vue, api/web/src/components/CloudTAK/Loading.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/Missions.vue, api/web/src/components/CloudTAK/Query/Reverse.vue, api/web/src/components/CloudTAK/Query/Weather.vue, api/web/src/components/CloudTAK/util/Coordinate.vue, api/web/src/components/CloudTAK/util/CoordinateType.vue, api/web/src/components/Lost.vue, api/web/src/stores/cots.ts, api/web/src/stores/cots/cot.ts
=> Coordinate Entry Type

api/lib/enums.ts, api/lib/schema.ts, api/lib/types.ts, api/migrations/0059_gorgeous_vector.sql, api/migrations/meta/0059_snapshot.json, api/migrations/meta/_journal.json, api/routes/profile.ts, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/SettingsDisplay.vue, api/web/src/components/CloudTAK/util/MenuTemplate.vue, api/web/src/derived-types.d.ts, api/web/src/stores/overlays/base.ts, api/web/src/stores/overlays/styles.ts
- **Add Text Size option**
- **DB Migration**
- **Setup UI**
- **Update Response types**
- **Make map size dynamic**
=> Text Accessibility

api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/util/CopyField.vue, api/web/src/components/CloudTAK/util/Phone.vue, api/web/src/stores/cots.ts, api/web/src/stores/cots/cot.ts, tasks/data/Dockerfile
- :rocket: Add copy-able phone value
- :rocket: Split phone field out to it's own component
- :rocket: Add `tel:` link for phone numbers
- :rocket: Move `COT.style` call into COT constructor and `update()` fn
=> Phone Comp

api/package-lock.json, api/web/package-lock.json, package-lock.json
Add basic support for visualizing TAK Routes
=> Add Routes

api/package-lock.json, api/package.json, cloudformation/lib/api.js
`forever` is no longer under development (least release > 2yrs) and it's building up dependencies with known issues. While these are not likely to be exploitable, switch to Docker restart instead.
=> Remove Forever

api/nginx.conf
=> Additional Headers

api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/Imports.vue, api/web/src/components/CloudTAK/util/Attachments.vue, api/web/src/components/CloudTAK/util/Contact.vue, api/web/src/components/CloudTAK/util/Feature.vue, api/web/src/components/CloudTAK/util/MultipleSelect.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/330
Closes: https://github.com/dfpc-coe/CloudTAK/issues/331
Closes: https://github.com/dfpc-coe/CloudTAK/issues/329
Closes: https://github.com/dfpc-coe/CloudTAK/issues/259
=> Add Search Offset

api/lib/enums.ts, api/lib/schema.ts, api/package-lock.json, api/routes/basemap.ts
Stronger types for Basemap objects and use new parsing module from `node-cot`
=> Vector Basemaps

api/lib/control/tilejson.ts, api/lib/enums.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/derived-types.d.ts, api/web/src/stores/map.ts
Enable Conditional support for 3D Terrain
=> 3D Terrain

api/web/package-lock.json, api/web/package.json, api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/map.ts
Thanks @JamesLMilner - https://github.com/JamesLMilner/terra-draw/
=> Sector Mode

api/lib/data-mission.ts, api/package-lock.json, api/web/src/components/DataEdit.vue, package-lock.json, package.json
- Fix mission subscription bug where a subscrition wasn't created immeditely
- Turn on Mission Diff by default when creating Machine User Data Syncs
=> Auto Subscribe

api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/Chat.vue
- Add Chat button from CoTView context to create a new chat
- Fix header of individual chat pane by using MenuTemplate component
=> Chat Button

api/routes/connection-data.ts, api/web/src/components/DataEdit.vue
Disallow PATCH requests that would result in the name change of a Data Sync.
=> Don't allow name changes

api/package-lock.json, api/routes/config.ts, api/routes/connection-data.ts, api/web/src/components/Admin/AdminConfig.vue, api/web/src/components/CloudTAK/Menu/SettingsCallsign.vue
Ref: https://github.com/dfpc-coe/CloudTAK/issues/321
=> Custom Group Names

api/web/src/components/CloudTAK/util/Video.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/364
=> Delete Video Lease

api/routes/video-lease.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue, api/web/src/components/CloudTAK/Menu/Videos.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/Video.vue, api/web/src/stores/map.ts, api/web/src/types.ts
- :tada: `UI` Add ability to renew lease & show if lease is expired
- :rocket: `UI` Show expired leases in Lease List
- :rocket: `API` Add ability to PATCH duration
- :rocket: Migrate VideoLeaseModal to TS
=> Video Lease Renewal

api/web/package-lock.json, api/web/src/App.vue, api/web/src/components/Admin.vue, api/web/src/components/Admin/AdminUser.vue, api/web/src/components/CloudTAK/Menu/Overlays.vue, api/web/src/components/Connection.vue, api/web/src/components/ConnectionEdit.vue, api/web/src/components/ConnectionSink.vue, api/web/src/components/ConnectionSinkEdit.vue, api/web/src/components/ConnectionSinks.vue, api/web/src/components/Connections.vue, api/web/src/components/Data.vue, api/web/src/components/DataEdit.vue, api/web/src/components/DataJob.vue, api/web/src/components/Layer.vue, api/web/src/components/LayerAlerts.vue, api/web/src/components/LayerEdit.vue, api/web/src/components/LayerQuery.vue, api/web/src/components/LayerQueryFeature.vue, tasks/pmtiles/src/index.ts
- :bug: `API` Add support for `%` decoding in PMTiles URL Validity Check
- :rocket `UI` Use `TablerIconButton` for buttons in Overlay manager to improve accessibility
=> PMTiles Improvements

api/lib/api/mission.ts, api/lib/aws/lambda.ts, api/package-lock.json, api/routes/marti-mission.ts, api/web/package-lock.json, api/web/src/components/Admin/AdminUser.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue, api/web/src/components/CloudTAK/Menu/Overlays.vue, api/web/src/components/CloudTAK/util/Feature.vue, api/web/src/components/CloudTAK/util/SelectFeats.vue, api/web/src/components/CloudTAK/util/Share.vue, api/web/src/derived-types.d.ts, api/web/src/stores/base/mission.ts, api/web/src/types.ts, cloudformation/CloudTAK.template.js, cloudformation/lib/api.js
- **Add TS Setup**
- **Update Lints**
=> Mission Editing

api/package-lock.json, api/package.json, api/routes/basemap.ts, api/routes/marti-package.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Basemaps.vue, api/web/src/components/CloudTAK/util/Share.vue, api/web/src/types.ts, package-lock.json
- :rocket: Migrate Basemaps to TS
- :rocket: Add ability to share basemap
=> Basemap Share

api/lib/api/files.ts, api/nginx.conf.js, api/package-lock.json, api/routes/marti-package.ts, api/start, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Mission.vue, api/web/src/components/CloudTAK/Menu/Package.vue, api/web/src/components/CloudTAK/util/SelectFeats.vue, api/web/src/components/CloudTAK/util/ShareToMission.vue, api/web/src/components/CloudTAK/util/ShareToPackage.vue, api/web/src/types.ts, cloudformation/CloudTAK.template.js, cloudformation/lib/api.js, cloudformation/lib/db.js
Sketch out the ability to create a Data Package from a selection of CoT markers
=> Create Data Package

api/routes/video-lease.ts, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu.vue, api/web/src/components/CloudTAK/Menu/Mission.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/MenuTemplate.vue, api/web/src/components/CloudTAK/util/ShareToPackage.vue, api/web/src/stores/base/mission.ts, api/web/src/stores/cots.ts, api/web/src/stores/map.ts
- :bug: Fix subscription bug where an unsubscribe wouldn't clean up the cotstore.subscription
- :tada: Allow subscribed missions to be exported as Data Packages
- :rocket: Migrate Mission menu to TS
-  :rocket: Migrate Menu to TS
- :rocket: Increase non-admin lease time to 24 hours
=> Data Package from Mission

api/lib/provider.ts, api/lib/schema.ts, api/lib/tak-auth.ts, api/lib/types.ts, api/migrations/0068_panoramic_sugar_man.sql, api/migrations/meta/0068_snapshot.json, api/migrations/meta/_journal.json, api/package-lock.json, api/routes/ldap.ts, api/routes/marti.ts, api/routes/server.ts, api/web/src/components/Admin.vue, api/web/src/components/Admin/AdminServer.vue, api/web/src/components/Configure.vue, api/web/src/components/Connection.vue, api/web/src/derived-types.d.ts
If WebTAK and the publicly signed API are not hosted on port 443 then CloudTAK will not allow initial configuration to proceed. 
This PR implements a `server.webtak` value for storing the underling webtak URL (traditionally on 443 or 8446) and respects it when using the API internally instead of the previous behavior of stripping out the port value from the Marti API.
=> Webtak api

api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/CopyField.vue, api/web/src/components/CloudTAK/util/Feature.vue
- Get an render icons on a feature point if they are present in MapLibre Spritesheets
=> MapLibre Icons in Feature Component

api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/CopyField.vue
- **Remarks Editing**
- **Proper Height if rows > 1**
- **Add ability to edit remarks**
- **Fix Lints**
=> Remarks Editing

api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/Breadcrumb.vue
- Ensure duplicate IDs aren't added to the locked array, resulting in an unexpected lock state.
- Significant improvements to the Breadcrumb Tool
-
=> Locking Behavior & Breadcrumb Tool

CHANGELOG.md, api/lib/aws/s3.ts, api/lib/config.ts, api/lib/types.ts, api/migrations/0074_eminent_stick.sql, api/migrations/meta/0074_snapshot.json, api/migrations/meta/_journal.json, api/package-lock.json, api/routes/profile-overlays.ts, api/web/package-lock.json, api/web/src/components/Admin/Videos/AdminVideoLeases.vue, api/web/src/components/Connection/AgencySelect.vue, cloudformation/lib/pmtiles.js, package-lock.json, package.json, tasks/data/package-lock.json, tasks/events/package-lock.json, tasks/pmtiles/package-lock.json, tasks/pmtiles/package.json, tasks/pmtiles/src/index.ts, tasks/pmtiles/src/lib/auth.ts, tasks/pmtiles/src/lib/pmtiles.ts, tasks/pmtiles/src/lib/s3.ts, tasks/pmtiles/tsconfig.json
Rewrite PMTiles Tile handler to use express server and under the hood map API Gateway requests to express requests
This will accomplish the following
- Significantly cleaner codebase for future changes and improvements
- Dual Compatability between API Gateway and Docker Compose as a deploy target
=> PMTiles Dual Compat

api/lib/aws/alarm.ts, api/package-lock.json, api/web/src/components/Admin.vue, api/web/src/components/Connection.vue, api/web/src/components/Connection/ConnectionLayer.vue, api/web/src/components/Data.vue, api/web/src/components/DataEdit.vue, api/web/src/components/Layer.vue, api/web/src/components/LayerEdit.vue
=> Page Alarm State

api/lib/auth.ts, api/routes/basemap.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/Admin/AdminOverlays.vue, api/web/src/components/Admin/AdminOverlaysEdit.vue, api/web/src/components/Styling/Layer.vue, api/web/src/components/util/UserSelect.vue
- Implement User Select dropdown
- Allow assigning System/Private scope to basemaps via Admin Basemaps console
- Allow assigning Username to Private Basemaps
=> User Select

api/lib/auth.ts, api/routes/login.ts, api/web/src/components/CloudTAK/util/DrawOverlay.vue, api/web/src/components/Login.vue
Username doesn't necessarily have to be email
=> Login Options

api/context, api/package-lock.json, api/package.json, api/web/src/components/Layer/LayerConfig.vue
- **Add Params**
- **Fix Context Script & Ensure cron toggle is off if no cron is present**
=> Webhook Papercuts

api/lib/models.ts, api/lib/schema.ts, api/lib/types.ts, api/migrations/0091_clammy_prodigy.sql, api/migrations/meta/0091_snapshot.json, api/migrations/meta/_journal.json, api/routes/connection-layer.ts, api/routes/errors.ts, api/test/fixtures/get_schema.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/Chat.vue, api/web/src/components/CloudTAK/Menu/Chats.vue, api/web/src/components/CloudTAK/Menu/Iconset.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue, api/web/src/components/Layer.vue, api/web/src/components/LayerEdit.vue, api/web/src/stores/base/cot.ts, api/web/src/stores/map.ts, package-lock.json
Allow setting an active mission in which features are automatically added
=> Make Active Mission

api/index.ts, api/lib/api/mission.ts, api/package-lock.json, api/routes/marti-mission.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Mission.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionTimeline.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionUsers.vue, api/web/src/components/CloudTAK/util/MenuTemplate.vue, api/web/src/std.ts
Allow users to export Missions in an Archive Format
=> Mission Archive Export

api/lib/control/tilejson.ts, api/package-lock.json, api/test/basemap.srv.test.ts, api/web/src/components/CloudTAK/Menu/Basemaps/EditModal.vue
- Improve Basemap editing modal w/ Variable Selection and fix scope bug
- Add native support for ESRI ImageServer querying
=> Basemap Improvements

api/routes/search.ts, api/web/package-lock.json, package-lock.json
The suggest endpoint was incorrectly truncating results
=> Fix Suggest

api/lib/esri.ts, api/lib/initialization.ts, api/package-lock.json, api/package.json, api/test/drop.ts, api/test/esri.srv.test.ts, cloudformation/lib/api.js
Add an integration testing class for basic ESRI functionality
=> ESRI Tests

api/web/package-lock.json, api/web/package.json, api/web/src/components/CloudTAK/Menu/Debugger.vue, api/web/src/components/CloudTAK/util/CopyField.vue, api/web/src/components/Connection/AgencySelect.vue, api/web/src/components/Connection/CertificateLogin.vue, api/web/src/components/Connection/CertificateMachineUser.vue, api/web/src/components/Layer/LayerEnvironment.vue, api/web/src/type.ts
Ref: https://github.com/dfpc-coe/CloudTAK/issues/536
=> Environment Update

api/web/src/components/CloudTAK/Menu/MenuChannels.vue, api/web/src/components/Configure.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/539
=> Use CloudTAK as configure logo

api/web/package-lock.json, api/web/src/components/CloudTAK/MainMenu.vue, api/web/src/components/CloudTAK/MapLoading.vue, api/web/src/components/CloudTAK/Menu/MenuFeatures.vue, api/web/src/components/CloudTAK/Menu/Overlays/TreeCots.vue, api/web/src/components/CloudTAK/QueryView.vue, api/web/src/components/CloudTAK/util/Attachments.vue, api/web/src/components/CloudTAK/util/Feature.vue, api/web/src/components/Login.vue, api/web/src/main.ts, api/web/src/workers/atlas-database.ts
Migrate the COT Explorer to support new async background database
=> Overlay CoT Explorer

api/web/src/base/cot.ts, api/web/src/base/events.ts, api/web/src/stores/map.ts, api/web/src/workers/atlas-connection.ts, api/web/src/workers/atlas-database.ts, api/web/src/workers/atlas-profile.ts, api/web/src/workers/atlas.ts
I had previously JSON STringified messages but further reading of the docs shows I can skip this step
Ref: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
=> Use Structured Clone on Post Message

api/web/package-lock.json, api/web/src/components/Admin/Videos/AdminVideoLeases.vue, api/web/src/components/CloudTAK/Menu/MenuVideos.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/Connection/ConnectionTokens.vue
Fixes: https://github.com/dfpc-coe/CloudTAK/issues/547
=> Video Lease :bug:

api/web/src/components/CloudTAK/Menu/MenuFeatures.vue, api/web/src/stores/map.ts
Add support for viewing feature tree in Feature Explorer Menu
=> Feature Tree

api/lib/control/video-service.ts, api/lib/enums.ts, api/lib/schema.ts, api/migrations/0093_wild_spectrum.sql, api/migrations/0094_striped_maginty.sql, api/migrations/meta/0093_snapshot.json, api/migrations/meta/0094_snapshot.json, api/migrations/meta/_journal.json, api/package-lock.json, api/routes/video-lease.ts, api/web/package-lock.json, api/web/src/components/Admin/Videos/AdminVideoLeases.vue, api/web/src/components/CloudTAK/Menu/MenuFeatures.vue, api/web/src/components/CloudTAK/Menu/MenuVideos.vue, api/web/src/components/CloudTAK/Menu/Videos/VideoLeaseModal.vue, api/web/src/components/CloudTAK/util/Video.vue, api/web/src/components/CloudTAK/util/VideoLeaseSourceType.vue, api/web/src/components/util/TableHeader.vue, api/web/src/derived-types.d.ts, api/web/src/stores/map.ts
- Encode Source Type & Model in VideoLease creation dialogue
- Show icons for Lease based on Video Lease Source Type
=> VideoLease Updates

api/package-lock.json, api/web/src/base/cot.ts, api/web/src/base/events.ts, api/web/src/components/Admin/AdminPalette.vue, api/web/src/components/Admin/AdminPaletteFeature.vue, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/MenuFeatures.vue, api/web/src/stores/map.ts, api/web/src/workers/atlas-database.ts
- **Add Search Options**
- **Update Features Menu**
=> Archive Events

api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/MenuFeatures.vue, api/web/src/components/CloudTAK/util/CoordinateType.vue, api/web/src/components/CloudTAK/util/Feature.vue, api/web/src/components/CloudTAK/util/FeatureIcon.vue
=> Refactor Feature => Feature & FeatureIcon

tasks/data/lib/kml.js, tasks/data/package-lock.json, tasks/data/package.json, tasks/data/test/fixtures.test.js, tasks/events/package-lock.json, tasks/events/src/index.ts, tasks/pmtiles/package-lock.json, tasks/pmtiles/package.json
@LizDepew Reported the Mesa Motherload failed to import.
Upon investigation this was due to a JPG file being reported as corrupted by the recently introduced iconset builder which is a precursor to full icon support in CloudTAK.
cc/ @LizDepew
=> Fix KML Import

cloudformation/lib/batch.js, package-lock.json, tasks/events/Dockerfile, tasks/events/package-lock.json, tasks/events/src/index.ts
The last big push to make the CloudTAK map interface fully functional outside of an AWS deploy is to do the following
cc/ @brian7704
=> Events Infra

api/lib/connection-pool.ts, api/lib/external.ts, api/lib/types.ts, api/package-lock.json, api/routes/connection.ts, api/routes/ldap.ts, api/test/fixtures/get_schema.json, api/test/flight.ts, api/web/package-lock.json, api/web/package.json, api/web/src/components/Connection.vue, api/web/src/components/Connection/AgencySelect.vue, api/web/src/components/Connection/CertificateMachineUser.vue, api/web/src/components/Connection/ConnectionGroups.vue, api/web/src/components/ConnectionEdit.vue, api/web/src/workers/atlas-team.ts, api/web/src/workers/atlas.ts
- :tada: Allow Machine User connections to have cert reissuance with a single button click
- :bug: Fix some bugs around connection state on PATCH requests
=> External Calls for Cert Expiry

api/package-lock.json, api/web/src/components/Loading.vue, api/web/src/components/Login.vue
Add a custom logo to the Loading interstitial when you first login to CloudTAK
=> Login Loading

api/lib/enums.ts, api/package-lock.json, api/routes/video-lease.ts, api/test/video-lease.src.test.ts
The media server needs to obtain all leases, not just `ephemeral: true/false`
As such, this PR introduces a trinary data structure called `AllBoolean` which 
represents `all, true, false`
=> Trainry VideoLease Param

tasks/pmtiles/package-lock.json, tasks/pmtiles/package.json, tasks/pmtiles/src/index.ts
Migrate to forked serverless which support express@5
=> Serverless

api/web/package-lock.json, api/web/src/components/CloudTAK/util/FeatureIcon.vue
Icon Rendering improvements to FeatureIcon component
=> Icon Rendering Component

api/package-lock.json, api/web/src/components/CloudTAK/Menu/MenuFiles.vue, api/web/src/types.ts
Duplicate file uploading that is enabled from MenuImports to also be shown in MenuFiles based on user feedback.
=> Add File Upload

api/package-lock.json, api/routes/server-injector.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/Admin/AdminServer.vue, api/web/src/components/Admin/Server/ServerConnection.vue, api/web/src/components/Admin/Server/ServerInjectors.vue, api/web/src/components/ServerAdmin.vue, api/web/src/derived-types.d.ts, api/web/src/main.ts, api/web/src/types.ts
=> COT Injectors in CloudTAK Admin UI

api/routes/server-injector.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/components/Admin/AdminUsers.vue, api/web/src/components/Admin/Server/ServerInjectorModal.vue, api/web/src/components/Admin/Server/ServerInjectors.vue, api/web/src/components/Admin/Videos/VideoConfigPath.vue, docker-compose.yml
- **Add Injector Management**
- **Server Injector Modal**
- **Add Injector APIs**
- **Complete Injector Support**
=> Injector Management

api/index.ts, api/lib/auth.ts, api/package-lock.json, api/package.json, api/routes/connection.ts, api/routes/types.ts, api/test/fixtures/get_schema.json, api/test/token.srv.test.ts, api/web/package-lock.json, api/web/package.json, api/web/src/components/Admin/AdminUsers.vue, api/web/src/components/Admin/Server/ServerInjectorModal.vue, api/web/src/components/Admin/Server/ServerInjectors.vue, api/web/src/components/Admin/Server/ServerRepeaters.vue, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/MenuContacts.vue, api/web/src/components/CloudTAK/util/PropertyType.vue, api/web/src/components/Connection/ConnectionGroups.vue, api/web/src/components/Connection/ConnectionLayer.vue, api/web/src/derived-types.d.ts, api/web/src/types.ts, api/web/src/workers/atlas-team.ts
Update the Contacts Menu to use the internal CloudTAK Message Plane
to recieve update commands to update the Contact List
=> Live Contacts

api/lib/control/video-service.ts
The RTSP protocol didn't return username/password compatible URL strings
=> Add RTSP Username/Password info

api/package-lock.json, api/routes/marti-mission.ts, api/test/fixtures/get_schema.json, api/web/package-lock.json, api/web/src/base/cot.ts, api/web/src/base/subscription.ts, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Notifications.vue, api/web/src/components/CloudTAK/util/PropertyType.vue, api/web/src/stores/map.ts, api/web/src/timediff.ts, api/web/src/workers/atlas-connection.ts, api/web/src/workers/atlas-database.ts, api/web/src/workers/atlas-team.ts
=> MissionCOTDelete

api/package-lock.json, api/web/src/base/subscription.ts, api/web/src/components/CloudTAK/Menu/MenuMission.vue, api/web/src/components/CloudTAK/Menu/MenuMissions.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerCreate.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerEdit.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerTree.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionTimeline.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionUsers.vue, api/web/src/types.ts
There were several locations in the UI, Server API, & underlying Node-TAK library that were not consistently using the MissionToken if is was provided resulting in 403 errors when accessing certain parts of the Mission UI
=> Mission Layer Token Support

api/web/src/components/CloudTAK/Map.vue, api/web/src/stores/map.ts
- :rocket: Hide return to home buttons when in default angle/orientation
- :tada: Introduce return to pitch button
Closes: https://github.com/dfpc-coe/CloudTAK/issues/641
=> Pitch/Rotate Home

api/web/src/components/CloudTAK/MainMenu.vue, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/Menu/MenuIconset.vue, api/web/src/components/CloudTAK/Menu/MenuRoutes.vue, api/web/src/components/CloudTAK/util/Icons.vue, api/web/src/components/util/IconSelect.vue
- Fix bugs related to Iconsets
=> Iconset Fixes

api/lib/models/Layer.ts, api/test/fixtures/get_schema.json, api/web/src/components/Layer/LayerOutgoingConfig.vue
- Introduces UI to add outgoing COT Filters - Closes: https://github.com/dfpc-coe/CloudTAK/issues/671
- Add ability to include a Content-Dispo on Connection Assets
=> Add Filter Expressions

api/routes/connection-asset.ts, api/web/src/components/Admin/AdminOverlays.vue
- :bug: Remove debug code - Closes: https://github.com/dfpc-coe/CloudTAK/issues/674
=> Remove Debug Code

api/web/package-lock.json, api/web/package.json, api/web/src/base/overlay.ts
I'm not entirely sure how the user got into this Map State but the user ended up with a basemap that included layers but no source object. When the user attempted to change their basemap the replacement failed as the `overlay.remove` has a `removeSource` call which threw an error.
This PR checks the Source existance before attempting to remove it.
=> Map Source Existance Check

api/web/src/derived-types.d.ts
=> Update Web Types

api/package-lock.json, api/routes/connection-video-lease.ts, api/web/src/components/Connection/ConnectionData.vue, api/web/src/components/Connection/ConnectionFiles.vue, api/web/src/components/Connection/ConnectionGroups.vue, api/web/src/components/Connection/ConnectionLayer.vue, api/web/src/components/Connection/ConnectionTokens.vue, api/web/src/components/Connection/ConnectionVideos.vue
- :bug: Ensure Connection Video Lease deletes are limited to that connection
=> Connection Limit

api/lib/schema.ts, api/package-lock.json, api/routes/connection-layer.ts, api/test/connection-channels.srv.test.ts, api/test/connection-layer.srv.test.ts, api/test/flight.ts, api/test/profile-chat.srv.test.ts, api/test/profile-overlay.srv.test.ts
Initial Connection Layer Unit Tests
=> Layer Unit Tests

api/index.ts, api/package.json, api/web/docs.html, api/web/package-lock.json, api/web/package.json, api/web/src/App.vue, api/web/src/components/Admin/AdminServer.vue, api/web/src/components/Admin/AdminUser.vue, api/web/src/components/Admin/AdminUsers.vue, api/web/src/components/Admin/Videos/AdminVideoTask.vue, api/web/src/components/CloudTAK/Menu/MenuContacts.vue, api/web/src/components/CloudTAK/Menu/MenuImports.vue, api/web/src/components/CloudTAK/Menu/MenuOverlays.vue, api/web/src/components/CloudTAK/Menu/MenuPackages.vue, api/web/src/components/CloudTAK/Menu/MenuSettings.vue, api/web/src/components/CloudTAK/Menu/MenuVideos.vue, api/web/src/components/CloudTAK/util/MenuTemplate.vue, api/web/src/components/Configure.vue, api/web/src/components/Connections.vue, api/web/src/components/LostUser.vue, api/web/src/components/ServerAdmin.vue, api/web/src/pages/docs/App.vue, api/web/src/pages/docs/main.ts
Migrate Swagger UI to it's own page
=> Web Hosted

api/routes/connection-layer.ts, api/routes/connection.ts, api/web/src/components/Connection.vue, api/web/src/components/Data.vue, api/web/src/components/Layer.vue
- **Move Invoke to incoming**
- **Update Loading Lints**
- **Setup Hydrated**
=> Move Invoke

api/package-lock.json, api/package.json, api/web/src/derived-types.d.ts, api/web/src/types.ts, cloudformation/CloudTAK.template.js
Adjust mission sync schema after seeing error
=> Mission Sync Adjustment

api/Dockerfile
Follow up to pr #741 and issue #740 
There was an issue with the mv command trying to move a directory into itself.
=> Follow up to pr #741 and issue #740  - Fixing mv command

api/lib/control/video-service.ts, api/routes/video-lease.ts
Allow PATCH updating an ephemeral lease with a new source URL
Ref: https://github.com/dfpc-coe/ops/issues/93
=> Simplify Video API Calls and support PATCH source updates

api/package-lock.json, api/web/package-lock.json, api/web/src/components/CloudTAK/Menu/Mission/MissionInfo.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/773
=> Mission Papercuts

api/routes/profile-features.ts, api/test/profile-feature-delete.test.ts, api/web/src/components/CloudTAK/Menu/MenuFeatures.vue, api/web/src/workers/atlas-database.ts
Allow deleting all features in your profile.
=> Profile Delete

api/web/src/components/CloudTAK/util/FloatingVideo.vue
The video player was experiencing playback failures when MediaMTX restarts the HLS muxer, which creates new segment naming and sequence resets. Additionally, the UI wasn't optimized for live streaming scenarios. Issues included:
- New segment prefixes (e.g., `d6b60e49ab09` → `dc95cd71e7a3`)
- Sequence number resets (both starting at 0)
- Player errors due to sequence mismatches
- Manual play required for live streams
- Inappropriate seek controls for live content
Enhanced the `FloatingVideo.vue` component with robust HLS error handling, recovery mechanisms, and live streaming optimizations:
- Implements 3-attempt retry system with delays: 1s, 2s, 4s
- Automatic recovery from network and media errors
- Proper cleanup and state reset between attempts
- Detects MediaMTX muxer restarts via …
=> Improve HLS Video Player Resilience and Live Streaming Experience

api/lib/control/tilejson.ts, tasks/data/package-lock.json, tasks/events/package-lock.json, tasks/events/package.json, tasks/events/src/import.ts, tasks/pmtiles/package-lock.json, tasks/pmtiles/src/index.ts, tasks/pmtiles/src/lib/pmtiles.ts, tasks/pmtiles/src/lib/tiles.ts
Implement fixes described in: https://github.com/dfpc-coe/CloudTAK/issues/803
Closes: https://github.com/dfpc-coe/CloudTAK/issues/803
=> Tile Cache Control

api/web/src/components/CloudTAK/util/DrawOverlay.vue
- :rocket: Add settings support for Draw Tools
- :rocket: Start to sketch out Lasso Target Layer to support choosing where features are being snipped from.
- :rocket: Force the user to set a callsign on first signin
=> Add Lasso Settings

api/web/package-lock.json, api/web/src/components/CloudTAK/util/PolygonArea.vue
Add additional area units as requested by Wildland Fire
=> Area Units

api/web/src/stores/map.ts, api/web/src/workers/atlas-profile.ts
Rebase https://github.com/dfpc-coe/CloudTAK/pull/866 out of the combined SIDC & Location updates to just include the location updates
- **fix: ensure users always report location to TAK server with GPS accuracy**
- **feat: add altitude support to location tracking**
- **fix: correct GPS accuracy mapping to circular error (CE) instead of HAE**
- **fix: revert CoT coordinates to 3-element format to resolve TAK server validation errors**
=> Fix Location Reporting

api/web/src/stores/modules/draw.ts
Closes: https://github.com/dfpc-coe/CloudTAK/issues/884
=> Fix Cursor State

api/web/src/components/CloudTAK/Map.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/885
=> Add IconMountain & Check for DEM

api/package-lock.json, api/routes/import.ts, api/routes/marti-video.ts, api/web/src/base/subscription.ts, api/web/src/components/Admin/AdminImports.vue, api/web/src/components/CloudTAK/Menu/MenuFiles.vue, api/web/src/workers/atlas-database.ts
- :bug: Wire up the Impersonation feature in the Imports API
- :bug: Fix recursion bug where deleting a CoT from a Mission would result in a Change Task which would then make an API call to delete the CoT from the mission, etc, etc, etc.
=> Import Impersonate

api/web/package-lock.json, api/web/src/base/cot.ts, api/web/src/components/CloudTAK/Map.vue, api/web/src/components/CloudTAK/util/Share.vue, api/web/src/components/CloudTAK/util/ShareToPackage.vue
Fixes: https://github.com/dfpc-coe/CloudTAK/issues/895
=> Vector Tile Feature ID

api/web/src/components/Admin/AdminConnections.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/903
=> Fix Connection Sorting

api/web/src/components/CloudTAK/MainMenu.vue, api/web/src/components/VideoWall/Main.vue, api/web/src/types.ts
Sketch out VideoWall initial API Calls
=> Video Wall Improvements

api/web/src/components/CloudTAK/Menu/MenuBasemaps.vue
Closes: https://github.com/dfpc-coe/CloudTAK/issues/875
=> Add Basemap Selection Indicator

cloudformation/lib/db.js
Modify underlying DB type to graviton instance for performance improvements and cost savings
=> Update DB Instance Type

api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/DrawTools.vue, api/web/src/components/CloudTAK/RangeRingsInput.vue, api/web/src/components/CloudTAK/util/PropertyDistance.vue
- :rocket: Rename Lost Person Behavior to "Range Rings"
- :bug: Fix distance calculation bug when distance unit was changed
- :tada: Allow adding any number of range rings
- :rocket: Remove Lost Person behavior hardcoded % names
cc/ @chriselsen @LongArmsLawrence
=> Range Rings

api/web/package-lock.json, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/util/FeatureIcon.vue, api/web/src/components/CloudTAK/util/PropertyType.vue
=> Cot Selection

api/web/package-lock.json, api/web/src/base/cot.ts, api/web/src/workers/atlas-database.ts
A user was primarily editing a Data Sync in CloudTAK when another EUD connected
and attempted to edit a feature. The CloudTAK instance correctly merged the change
but the pendingGuid log was not queried when recieving a message from another client
to determine if this was an external or internally authored change.
This resulted in the client adding the CoT to the subscription as a new CoT, triggering
a cascade of Mission Change Events.
=> Mission Update Recursion

.deploy, api/index.ts, api/lib/limits.ts, api/package-lock.json, api/routes/marti-mission-layers.ts, api/routes/marti-mission.ts, api/web/package-lock.json, api/web/src/base/cot.ts, api/web/src/base/subscription.ts, api/web/src/components/CloudTAK/CoTView.vue, api/web/src/components/CloudTAK/Menu/MenuMission.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionContents.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerCreate.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayerTree.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLayers.vue, api/web/src/components/CloudTAK/util/PropertyType.vue, api/web/src/components/CloudTAK/util/SettingsCallsign.vue, api/web/src/components/CloudTAK/util/ShareToPackage.vue, api/web/src/components/util/Upload.vue, api/web/src/stores/modules/draw.ts, api/web/src/workers/atlas-database.ts
- :rocket: Simplify Data Sync Layer Creation and only allow the creation of Groups (IE Folders) from the UI
- :bug: Fix MultiSelect on Data Sync CoTs by ensuring `.properties.id` is always populated on new CoTs
- :bug: Fix padding issue in Settings Menu when selecting `type` property
Closes: https://github.com/dfpc-coe/CloudTAK/issues/973
Closes: https://github.com/dfpc-coe/CloudTAK/issues/972
=> Update Data Sync Layers Modal

api/lib/certificate.ts, api/routes/connection.ts
Include the Certificate Chain in P12 Generation
=> P12 Generation - Include Chain

api/lib/schema.ts, api/routes/import.ts, api/web/src/components/Admin/AdminImports.vue
Allow System Admins to have access to Imports in the same way they have access to Data Packages or Missions for the purpose of debugging when an import fails
=> Admin Download

api/web/src/components/CloudTAK/util/PropertyAttachments.vue
=> Fix JPEG File extension parsing

api/web/src/components/ETL/Connection.vue, api/web/src/components/ETL/Connection/StatusDot.vue
- :rocket: `UI` Use Network icon to show External Connections vs Paused Cloud Connections
- :tada: Allow downloading the generated TrustStore
=> Truststore Download

api/lib/certificate.ts, api/routes/connection.ts, api/web/src/components/ETL/Connection.vue
Require setting a password to be able to download the Connection Certificate/Truststore
=> Password Truststore/Cert

api/package-lock.json, api/web/src/base/subscription.ts, api/web/src/components/Admin/AdminImports.vue, api/web/src/components/CloudTAK/Menu/Mission/MissionLogs.vue, api/web/src/components/CloudTAK/util/CopyField.vue, api/web/src/components/CloudTAK/util/TagEntry.vue, api/web/src/components/ETL/Connection.vue
- :rocket: Wrap Mission Logs to ensure they are fully visible - Closes: https://github.com/dfpc-coe/CloudTAK/issues/1022
- :tada: Allow editing Mission Logs
- :rocket: Add `deletable` prop in CopyField.vue
- :bug: Fix PATCH Mission Log API, the underlying API Call in node-tak didn't include the log ID
=> Add Ability to delete from CopyField
